# Generated by Django 4.1.7 on 2023-03-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='interval',
            field=models.CharField(default='1s', editable=False, max_length=8),
        ),
    ]
