# Generated by Django 4.1.7 on 2023-04-04 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alarm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_high_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_low_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='UA', unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='coin',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='short_name_coin',
        ),
        migrations.AddField(
            model_name='coin',
            name='abbreviation',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
        migrations.AddField(
            model_name='candle',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alarm.coin'),
        ),
        migrations.AddField(
            model_name='coin',
            name='phone',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alarm.phone'),
        ),
    ]
