# Generated by Django 4.1.7 on 2023-03-28 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_high_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_low_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alarm.coin')),
            ],
        ),
    ]
