# Generated by Django 4.1.7 on 2023-04-04 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0003_rename_last_high_price_candle_high_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candle', to='alarm.coin'),
        ),
    ]
