# Generated by Django 4.1.7 on 2023-04-10 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0004_alter_candle_coin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_pair', models.CharField(max_length=255)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alarm.phone')),
            ],
        ),
        migrations.AlterField(
            model_name='candle',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candle', to='alarm.threshold'),
        ),
        migrations.DeleteModel(
            name='Coin',
        ),
    ]
