# Generated by Django 4.1.7 on 2023-04-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0005_threshold_alter_candle_coin_delete_coin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threshold',
            old_name='threshold',
            new_name='price',
        ),
    ]
