# Generated by Django 4.1.7 on 2023-04-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0007_candle_trade_pair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candle',
            name='coin',
        ),
    ]
