# Generated by Django 4.1.7 on 2023-04-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0008_remove_candle_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
