# Generated by Django 4.1.7 on 2023-04-13 14:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0009_candle_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdBrake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happened_at', models.DateTimeField(auto_created=datetime.time)),
                ('threshold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alarm.threshold')),
            ],
        ),
    ]
