# Generated by Django 4.1.7 on 2023-04-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0010_thresholdbrake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thresholdbrake',
            name='happened_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
