# Generated by Django 4.1.7 on 2023-04-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0011_alter_thresholdbrake_happened_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thresholdbrake',
            name='happened_at',
        ),
    ]
