# Generated by Django 4.1.7 on 2023-04-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0015_alter_thresholdbrake_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thresholdbrake',
            name='message',
        ),
        migrations.AddField(
            model_name='phone',
            name='message',
            field=models.TextField(default=None),
        ),
    ]
