# Generated by Django 4.1.7 on 2023-05-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0016_remove_thresholdbrake_message_phone_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
