# Generated by Django 4.1.7 on 2023-06-01 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0017_alter_phone_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='alarm.phone'),
        ),
        migrations.AlterUniqueTogether(
            name='threshold',
            unique_together={('phone', 'trade_pair', 'price')},
        ),
    ]
