# Generated by Django 4.1.7 on 2023-06-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0018_alter_threshold_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='close_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
