# Generated by Django 4.1.7 on 2023-06-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0019_candle_close_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='thresholdbrake',
            name='user_notified',
            field=models.BooleanField(default=False),
        ),
    ]
