# Generated by Django 4.1.7 on 2023-06-16 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0020_thresholdbrake_user_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='thresholdbrake',
            name='threshold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threshold_brakes', to='alarm.threshold'),
        ),
    ]
