# Generated by Django 4.1.7 on 2023-06-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0021_phone_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='telegram_chat_id',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
