# Generated by Django 4.1.7 on 2023-06-16 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0025_phone_active_twilio_call_sid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='active_twilio_call_sid',
            new_name='ringing_twilio_call_sid',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='message',
        ),
    ]
