# Generated by Django 4.1.7 on 2023-06-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0026_rename_active_twilio_call_sid_phone_ringing_twilio_call_sid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='ringing_twilio_call_sid',
            new_name='twilio_call_sid',
        ),
        migrations.AddField(
            model_name='phone',
            name='telegram_message_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
