# Generated by Django 4.1.7 on 2023-06-18 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0028_alter_phone_twilio_call_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thresholdbrake',
            name='threshold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threshold_brakes', to='alarm.threshold'),
        ),
    ]
