# Generated by Django 4.1.7 on 2023-06-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0029_alter_thresholdbrake_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='paused_until',
            field=models.DateTimeField(null=True),
        ),
    ]
