# Generated by Django 4.1.7 on 2023-06-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0030_phone_paused_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='paused_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='telegram_message_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='twilio_call_sid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
