# Generated by Django 4.1.7 on 2023-06-25 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0034_thresholdbreak_delete_thresholdbrake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thresholdbreak',
            name='threshold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threshold_breaks', to='alarm.threshold'),
        ),
    ]
