# Generated by Django 4.1.7 on 2023-06-25 21:18

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0035_alter_thresholdbreak_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UA', unique=True),
        ),
    ]
