# Generated by Django 4.1.7 on 2023-06-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0036_alter_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='pause_minutes_duration',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
