# Generated by Django 4.1.7 on 2023-06-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0037_phone_pause_minutes_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='pause_minutes_duration',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
