# Generated by Django 4.1.7 on 2023-06-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0038_alter_phone_pause_minutes_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
