# Generated by Django 4.1.7 on 2023-07-07 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0041_auto_20230626_0314'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='threshold',
            unique_together=set(),
        ),
    ]
