# Generated by Django 4.1.7 on 2023-09-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0042_alter_threshold_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
